export const functions = [
  {
    name: 'import_components',
    description: 'Imports all listed React components from `@/components/ui`',
    parameters: {
      type: 'object',
      properties: {
        components: {
          type: 'string',
          description: 'Names of React components separated by spaces to import, for example `navigation-menu alert button`',
          enum: [
            `alert`,
            `alert-dialog`,
            `aspect-ratio`,
            `avatar`,
            `badge`,
            `button`,
            `calendar`,
            `card`,
            `checkbox`,
            `collapsible`,
            `combobox`,
            `command`,
            `context-menu`,
            `data-table`,
            `date-picker`,
            `dialog`,
            `dropdown-menu`,
            `form`,
            `hover-card`,
            `input`,
            `label`,
            `menubar`,
            `navigation-menu`,
            `popover`,
            `progress`,
            `radio-group`,
            `scroll-area`,
            `select`,
            `separator`,
            `sheet`,
            `skeleton`,
            `slider`,
            `switch`,
            `table`,
            `tabs`,
            `textarea`,
            `toast`,
            `toggle`,
            `tooltip`,
          ]
        },
      },
      required: ['component'],
    },
  },
  {
    name: 'write_jsx',
    description: 'Inserts the JSX code into the `return` statement of the React component',
    parameters: {
      type: 'object',
      properties: {
        code: {
          type: 'string',
          description: 'The JSX code without any JavaScript logic',
        },
      },
    },
    required: ['code'],
  },
];
